language: perl
install:
script: make -j `nproc` && make test && make release
env:
  global:
    secure: jK5oSckHD3h+gKlkzB81TGdFmhO78HiUKk/BCV5PMWVeEwJfS+FeA8Sxj52atnE5BP8pIIWt50uxhZZ0WM3QmXZeo7LCBm5YWj+EHFIf/N157YOV710B7biyesydPvSScHFdwapgv8b7TlyBPn24Gm6bW+daynVE03BgRYK4Klc=
after_success: .travis/github-release.sh "$TRAVIS_REPO_SLUG" "`head -1 src/VERSION`" build/release/*
